name = "tidyfeed-admin"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

# ğŸ‘‡ è¿™ä¸€è¡Œå°±æ˜¯ç”¨æ¥æ›¿ä»£ç•Œé¢ä¸Šé‚£ä¸ªâ€œBuild output directoryâ€é€‰é¡¹çš„
pages_build_output_dir = ".vercel/output/static"