name = "tidyfeed-adminpro"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

# ğŸ‘‡ è¿™ä¸€è¡Œå°±æ˜¯ç”¨æ¥æ›¿ä»£ç•Œé¢ä¸Šé‚£ä¸ªâ€œBuild output directoryâ€é€‰é¡¹çš„
pages_build_output_dir = ".vercel/output/static"

# Environment Variables
[vars]
NEXT_PUBLIC_API_URL = "https://api.tidyfeed.app"